### PR TITLE
clean up, moved more functions to tools.py

### PR DESCRIPTION
**Pull request by jhfrost314**

### CODE REVIEW

**Comment by albalu** [comment]
ready to merge? passed the unittest?

**Comment by jhfrost314** [comment]
How do you run the unit test? I ran AMSET normally and everything looks good, but test_amset.py only seems to define a test without running it, so I'm a little confused.

**Comment by albalu** [comment]
run 'Unittests in AmsetTest' in test_amset.py it makes sure the values of the mobility have not changed after the changes you made. Currently, it only tests egrid integration, please also add your tests that test the kgrid integration values.

**Comment by jhfrost314** [comment]
Sorry I tried again but I still don't understand how to actually run it. I tried adding the lines
`test_object = AmsetTest()`
`test_object.setUp()`
`test_object.test_GaAs`
at the end of test_amset.py, but I got an error.

**Pull request merged**
